version: 2.1
jobs:
  build_and_test:
    macos:
      xcode: 15.3.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run:
          name: Show Xcode version
          command: xcodebuild -version
      - run:
          name: Show available destinations
          command: xcrun simctl list devices
      - run:
          name: Create Simulator
          command: xcrun simctl create "iPhone 15 Pro" "com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro" "com.apple.CoreSimulator.SimRuntime.iOS-17-4"
      - run:
          name: Boot Simulator
          command: xcrun simctl boot "iPhone 15 Pro"
      - run:
          name: Build Project
          command: xcodebuild -project ToDoListApp.xcodeproj -scheme ToDoListApp -destination 'platform=iOS Simulator,OS=17.4,name=iPhone 15 Pro' build
      - run:
          name: Run Tests
          command: xcodebuild -project ToDoListApp.xcodeproj -scheme ToDoListApp -destination 'platform=iOS Simulator,OS=17.4,name=iPhone 15 Pro' test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
