version: 2.1
jobs:
  build:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: Build Project
          command: xcodebuild -project ToDoListApp.xcodeproj -scheme ToDoListApp -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 12' build
      - run:
          name: Run Tests
          command: xcodebuild -project ToDoListApp.xcodeproj -scheme ToDoListApp -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 12' test
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
