version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "12.5.1"
    environment:
      RUBY_VERSION: "3.0.0"

jobs:
  build-and-test:
    executor: macos-executor
    steps:
      - checkout
      - run:
          name: Install RVM
          command: curl -sSL https://get.rvm.io | bash -s stable
      - run:
          name: Install Ruby
          command: rvm install $RUBY_VERSION

      - run:
          name: Install Bundler
          command: gem install bundler -v 2.4.22
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Install CocoaPods
          command: pod install --repo-update
      - run:
          name: Build and Test with Fastlane
          command: bundle exec fastlane ios build_and_test
      - store_test_results:
          path: fastlane/test_output
      - store_artifacts:
          path: fastlane/test_output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
