version: 2.1
jobs:
  build_and_test:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run: xcodebuild -version
      - run:
          name: Show available destinations
          command: xcrun simctl list devices
      - run:
          name: Build Project
          command: xcodebuild -project ToDoListApp.xcodeproj -scheme ToDoListApp -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
