version: 2.1
jobs:
  build_and_test:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run: xcodebuild -version
      - run:
          name: Show available destinations
          command: xcrun simctl list devices
      - run:
          name: Fastlane test #Build Project
          command: fastlane ios test #xcodebuild -project ToDoListApp.xcodeproj -scheme ToDoListApp clean build -allowProvisioningUpdates

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
