version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "12.5.1"
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: sudo gem install bundler
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Install CocoaPods
          command: pod install --repo-update
      - run:
          name: Build and Test with Fastlane
          command: bundle exec fastlane ios build_and_test
      - store_test_results:
          path: fastlane/test_output
      - store_artifacts:
          path: fastlane/test_output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
#
