version: 2.1
jobs:
  build_and_test:
  macos:
    xcode: 14.2.0
  resource_class: macos.m1.medium.gen1

  steps:
    - checkout
    - run: xcodebuild -version
    - run:
        name: Build Project
        command: xcodebuild -project ToDoListApp.xcodeproj -scheme ToDoListApp -destination 'platform=iOS Simulator,OS=17.4,name=iPhone 15 Pro' build -allowProvisioningUpdates

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
