# fastlane/Fastfile
default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      devices: ["iPhone 11"], # Spezifiziere ein verfügbares Gerät
      clean: true,
      output_directory: ENV['FL_OUTPUT_DIR']
    )
  end

  desc "Ad-hoc build"
  lane :adhoc do
    match(type: "adhoc")
    gym(
      export_method: "ad-hoc",
      output_directory: ENV['FL_OUTPUT_DIR']
    )
  end
end
